import { useRef, useState } from 'react';
import type { UserState } from '../types';
import { isState } from '../utils/storage';
import { fullDate } from '../utils/date';

export function DataPage({ state, onExport, onImport, onReset, onSettings }: { state: UserState; onExport: () => void; onImport: (value: UserState) => void; onReset: () => void; onSettings: (patch: Partial<UserState['settings']>) => void }) {
  const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState('');
  const exportData = () => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `kontur-appsec-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); onExport(); setMessage('Резервная копия скачана.'); };
  const importData = async (file?: File) => { if (!file) return; try { const parsed: unknown = JSON.parse(await file.text()); if (!isState(parsed)) throw new Error(); onImport(parsed); setMessage('Данные импортированы и проверены.'); } catch { setMessage('Не удалось импортировать файл: ожидается корректная резервная копия КОНТУР v1.'); } if (input.current) input.current.value = ''; };
  return <div className="page"><header className="page-heading"><p className="eyebrow">УПРАВЛЕНИЕ ЛОКАЛЬНЫМИ ДАННЫМИ</p><h1>Данные</h1><p>Все записи хранятся только в этом браузере. Периодически экспортируй резервную копию.</p></header><div className="data-grid"><section><h2>Резервная копия</h2><p>Последний экспорт: {state.backup.lastExportAt ? fullDate(state.backup.lastExportAt.slice(0, 10)) : 'ещё не выполнялся'}.</p><button className="primary" onClick={exportData}>ЭКСПОРТ JSON</button><input ref={input} type="file" accept="application/json" onChange={event => importData(event.target.files?.[0])} /><button onClick={() => input.current?.click()}>ИМПОРТ JSON</button>{message && <p className="saved">{message}</p>}</section><section><h2>Настройки консоли</h2><label className="setting">Начало учебного пути<input type="date" value={state.settings.startDate} onChange={event => onSettings({ startDate: event.target.value })} /></label><label className="setting">Цель на неделю, мин<input type="number" min="0" step="15" value={state.settings.weeklyTarget} onChange={event => onSettings({ weeklyTarget: Number(event.target.value) })} /></label><label className="switch"><input type="checkbox" checked={state.settings.crtEnabled} onChange={event => onSettings({ crtEnabled: event.target.checked })} /> Эффект старого монитора</label><label className="switch"><input type="checkbox" checked={state.settings.compactMode} onChange={event => onSettings({ compactMode: event.target.checked })} /> Компактный режим</label></section><section className="reset"><h2>Сбросить прогресс</h2><p>Удалит статусы, заметки, журнал и очередь повторения только в текущем браузере.</p><button className="danger" onClick={() => { if (confirm('Первое подтверждение: удалить весь пользовательский прогресс?') && confirm('Второе подтверждение: экспорт уже сделан и данные точно нужно удалить?')) onReset(); }}>СБРОСИТЬ ПРОГРЕСС</button></section></div></div>;
}
