import { useEffect, useRef, useState, type CSSProperties } from 'react';

type Mode = 'focus' | 'short' | 'long';
interface TimerConfig { focus: number; short: number; long: number; cyclesBeforeLong: number; soundEnabled: boolean; }
const configKey = 'appsec-console-pomodoro-v1';
const runningKey = 'appsec-console-pomodoro-running-v1';
const defaults: TimerConfig = { focus: 25, short: 5, long: 15, cyclesBeforeLong: 4, soundEnabled: true };
const modeTitle: Record<Mode, string> = { focus: 'ФОКУС-СЕССИЯ', short: 'КОРОТКИЙ ПЕРЕРЫВ', long: 'ДЛИННЫЙ ПЕРЕРЫВ' };

function readConfig(): TimerConfig { try { const value: unknown = JSON.parse(localStorage.getItem(configKey) ?? ''); if (!value || typeof value !== 'object') return defaults; const item = value as Partial<TimerConfig>; return { ...defaults, ...item }; } catch { return defaults; } }
function readRunning(): { mode: Mode; endsAt: number; completed: number } | undefined { try { const value: unknown = JSON.parse(localStorage.getItem(runningKey) ?? ''); if (!value || typeof value !== 'object') return undefined; const item = value as { mode?: Mode; endsAt?: number; completed?: number }; return item.mode && typeof item.endsAt === 'number' && typeof item.completed === 'number' ? { mode: item.mode, endsAt: item.endsAt, completed: item.completed } : undefined; } catch { return undefined; } }
function pad(value: number): string { return String(Math.max(0, value)).padStart(2, '0'); }
export function PomodoroPage() {
  const saved = readRunning(); const [config, setConfig] = useState<TimerConfig>(readConfig); const [mode, setMode] = useState<Mode>(saved?.mode ?? 'focus'); const [endsAt, setEndsAt] = useState<number | undefined>(saved?.endsAt); const [remaining, setRemaining] = useState(saved ? Math.max(0, Math.ceil((saved.endsAt - Date.now()) / 1000)) : config.focus * 60); const [completed, setCompleted] = useState(saved?.completed ?? 0); const audio = useRef<AudioContext | null>(null);
  const total = config[mode] * 60; const isRunning = endsAt !== undefined;
  useEffect(() => { localStorage.setItem(configKey, JSON.stringify(config)); }, [config]);
  useEffect(() => { if (!endsAt) return; const update = () => { const next = Math.max(0, Math.ceil((endsAt - Date.now()) / 1000)); setRemaining(next); if (next === 0) { setEndsAt(undefined); localStorage.removeItem(runningKey); if (config.soundEnabled) alarm(); if (mode === 'focus') setCompleted(value => value + 1); } }; update(); const interval = window.setInterval(update, 500); return () => clearInterval(interval); }, [endsAt, config.soundEnabled, mode]);
  useEffect(() => { if (!endsAt) return; localStorage.setItem(runningKey, JSON.stringify({ mode, endsAt, completed })); }, [endsAt, mode, completed]);
  useEffect(() => { if (!isRunning) setRemaining(config[mode] * 60); }, [config, mode, isRunning]);
  const alarm = () => { try { const context = audio.current ?? new AudioContext(); audio.current = context; const beep = (offset: number) => { const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = 660; gain.gain.setValueAtTime(.0001, context.currentTime + offset); gain.gain.exponentialRampToValueAtTime(.15, context.currentTime + offset + .02); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + offset + .23); oscillator.connect(gain).connect(context.destination); oscillator.start(context.currentTime + offset); oscillator.stop(context.currentTime + offset + .25); }; beep(0); beep(.32); } catch { /* Audio may be blocked by the browser */ } };
  const start = () => { try { const context = audio.current ?? new AudioContext(); audio.current = context; void context.resume(); } catch { /* Continue without audio */ } setEndsAt(Date.now() + (remaining || total) * 1000); if (remaining === 0) setRemaining(total); };
  const pause = () => { setEndsAt(undefined); localStorage.removeItem(runningKey); };
  const reset = () => { pause(); setRemaining(total); };
  const selectMode = (next: Mode) => { pause(); setMode(next); setRemaining(config[next] * 60); };
  const finish = () => { pause(); if (config.soundEnabled) alarm(); if (mode === 'focus') setCompleted(value => value + 1); setRemaining(0); };
  const percentage = total ? Math.min(100, remaining / total * 100) : 0;
  const nextBreak = completed + 1 >= config.cyclesBeforeLong ? 'длинный перерыв' : 'короткий перерыв';
  return <div className="page pomodoro"><header className="page-heading"><p className="eyebrow">ПРОТОКОЛ ФОКУСА // ЛОКАЛЬНЫЙ ТАЙМЕР</p><h1>Таймер «Помодоро»</h1><p>Таймер продолжает отсчёт по реальному времени, пока ты работаешь в другой вкладке или свернул браузер. По завершении он подаст звуковой сигнал.</p></header><section className="pomodoro-layout"><div className="timer-module"><div className="timer-modes">{(['focus','short','long'] as Mode[]).map(item => <button key={item} className={mode === item ? 'active' : ''} onClick={() => selectMode(item)} disabled={isRunning}>{modeTitle[item]}</button>)}</div><div className="timer-display" style={{ '--progress': `${percentage}%` } as CSSProperties}><span>{pad(Math.floor(remaining / 60))}:{pad(remaining % 60)}</span><small>{isRunning ? 'СЕССИЯ ИДЁТ' : remaining === 0 ? 'СЕССИЯ ЗАВЕРШЕНА' : 'ГОТОВ К СТАРТУ'}</small></div><div className="timer-actions">{isRunning ? <button className="primary" onClick={pause}>ПАУЗА</button> : <button className="primary" onClick={start}>{remaining === 0 ? 'НОВАЯ СЕССИЯ' : 'СТАРТ'}</button>}<button onClick={reset}>СБРОС</button><button onClick={finish} disabled={!isRunning}>ЗАВЕРШИТЬ</button></div></div><aside className="pomodoro-side"><p className="eyebrow">СТАТУС ЦИКЛА</p><h2>{completed} фокус-сессий</h2><p>Следующий переход: {nextBreak}. Таймер не создаёт журнал автоматически: сохраняй реальный результат в «Сегодня» после работы.</p><div className="pomodoro-note"><b>ФОНОВЫЙ РЕЖИМ ГОТОВ</b><span>Отсчёт не зависит от открытой вкладки. Звук может быть ограничен настройками браузера или ОС.</span></div></aside></section><section className="pomodoro-settings"><p className="eyebrow">ПАРАМЕТРЫ ТАЙМЕРА // МИНУТЫ</p><div>{([['focus','Фокус'],['short','Короткий перерыв'],['long','Длинный перерыв']] as const).map(([key,label]) => <label key={key}>{label}<input type="number" min="1" max="180" value={config[key]} disabled={isRunning} onChange={event => setConfig(value => ({...value, [key]: Math.max(1, Number(event.target.value) || 1)}))} /> мин</label>)}<label>Длинный перерыв после<input type="number" min="1" max="12" value={config.cyclesBeforeLong} disabled={isRunning} onChange={event => setConfig(value => ({...value, cyclesBeforeLong: Math.max(1, Number(event.target.value) || 1)}))} /> сессий</label><label className="switch">Звук по завершении<input type="checkbox" checked={config.soundEnabled} onChange={event => setConfig(value => ({...value, soundEnabled:event.target.checked}))} /></label></div></section></div>;
}
