import { useMemo, useState } from 'react';
import { topicById, topics } from '../data/curriculum';
import type { DailyLog, UserState } from '../types';
import { dateKey, minutesText } from '../utils/date';
import { activeDays, longestStreak, mostStudiedArea, statusCount, totalMinutes } from '../utils/insights';

type Period = 'today' | 'week' | 'month';
const periodDays: Record<Period, number> = { today: 1, week: 7, month: 30 };
export function ReportPage({ state }: { state: UserState }) {
  const [period, setPeriod] = useState<Period>('today'); const logs = useMemo(() => state.dailyLogs.filter(log => Math.floor((new Date(`${dateKey()}T12:00:00`).getTime() - new Date(`${log.date}T12:00:00`).getTime()) / 86400000) < periodDays[period]), [state.dailyLogs, period]); const report = makeReport(logs, period); const copy = async () => { try { await navigator.clipboard.writeText(report); } catch { /* Clipboard unavailable */ } }; const weekLogs = state.dailyLogs.filter(log => Math.floor((new Date(`${dateKey()}T12:00:00`).getTime() - new Date(`${log.date}T12:00:00`).getTime()) / 86400000) < 7); const practical = topics.filter(topic => state.progress[topic.id]?.status === 2).length;
  return <div className="page"><header className="page-heading"><p className="eyebrow">СВОДКА // ЛОКАЛЬНЫЙ ОТЧЁТ</p><h1>Отчёт</h1><p>Шаблонный текст из твоих заметок — без искусственного интеллекта, API и лишней обработки данных.</p></header><div className="report-tabs">{(['today', 'week', 'month'] as Period[]).map(item => <button key={item} className={period === item ? 'active' : ''} onClick={() => setPeriod(item)}>{{ today: 'Сегодня', week: 'За неделю', month: 'За месяц' }[item]}</button>)}</div><section className="report-paper"><pre>{report}</pre><button className="primary" onClick={copy}>КОПИРОВАТЬ</button></section><section className="weekly"><p className="eyebrow">ЕЖЕНЕДЕЛЬНАЯ СВОДКА</p><h2>Сводка недели</h2><div className="dashboard-grid"><article><b>{activeDays(weekLogs)}<small> дней занимался</small></b><p>{minutesText(totalMinutes(weekLogs))} суммарно.</p></article><article><b>{[...new Set(weekLogs.flatMap(log => log.topicIds))].length}<small> тем затронуто</small></b><p>Практиковал: {practical}; могу объяснить: {statusCount(state, 3)}.</p></article><article><b>{mostStudiedArea(state)}<small> главный фокус</small></b><p>Максимальная серия: {longestStreak(state.dailyLogs)} дней.</p></article></div><h3>Что осталось непонятным</h3><ul>{weekLogs.filter(log => log.unclear).slice(0, 5).map(log => <li key={log.id}>{log.unclear}</li>)}{!weekLogs.some(log => log.unclear) && <li>Неясностей пока не записано.</li>}</ul><p className="recommendation">Рекомендация: продолжи с первой темой текущего этапа или с очереди повторения — так план не распадается на случайные вкладки.</p></section></div>;
}
function makeReport(logs: DailyLog[], period: Period): string { const minutes = totalMinutes(logs); const unique = [...new Set(logs.flatMap(log => log.topicIds))].map(id => topicById[id]?.title).filter(Boolean); const learned = logs.map(log => log.learned).filter(Boolean); const practiced = logs.map(log => log.practiced).filter(Boolean); const unclear = logs.map(log => log.unclear).filter(Boolean); const heading = period === 'today' ? 'Сегодня' : period === 'week' ? 'За эту неделю' : 'За этот месяц'; if (!logs.length) return `${heading} учебных записей пока нет.\n\nКогда появится первая сессия, здесь автоматически сложится аккуратный отчёт.`; return `${heading} занимался AppSec ${minutesText(minutes)}.\n\nРазобрал: ${unique.join(', ') || 'учебные материалы'}.\n\nГлавное, что понял: ${learned.join(' ') || 'запись пока без краткого вывода.'}\n\nПрактика: ${practiced.join(' ') || 'практику пока не записывал.'}\n\nПока не до конца понял: ${unclear.join(' ') || 'вопросов не осталось.'}`; }
