import { useMemo, useState } from 'react';
import { stages, topicById } from '../data/curriculum';
import type { Area, UserState } from '../types';
import { ProgressBar } from '../components/ProgressBar';
const filters: Array<{ label: string; value: string }> = [{ label: 'Все', value: 'all' }, { label: 'Не начато', value: '0' }, { label: 'Изучаю', value: '1' }, { label: 'Практиковал', value: '2' }, { label: 'Могу объяснить', value: '3' }, { label: 'На повторение', value: 'due' }, { label: 'Web', value: 'WEB' }, { label: 'Code', value: 'CODE' }, { label: 'AppSec', value: 'APPSEC' }, { label: 'DevSecOps', value: 'DEVSECOPS' }, { label: 'Architecture', value: 'ARCHITECTURE' }];
export function RoadmapPage({ state, onTopic, onCheckpoint }: { state: UserState; onTopic: (id: string) => void; onCheckpoint: (id: string, value: 0|1|2) => void }) {
  const [filter, setFilter] = useState('all'); const today = new Date().toISOString().slice(0,10);
  const shown = useMemo(() => stages.map(stage => ({ stage, items: stage.topicIds.map(id => topicById[id]).filter(topic => filter === 'all' || (['0','1','2','3'].includes(filter) && String(state.progress[topic.id]?.status ?? 0) === filter) || (filter === 'due' && state.reviews[topic.id]?.nextReview <= today) || topic.area === filter as Area) })).filter(group => group.items.length), [filter, state, today]);
  return <div className="page"><header className="page-heading"><p className="eyebrow">TRACK // WEB-SEC</p><h1>Маршрут на 12 месяцев</h1><p>Этапы можно открывать в любом порядке. Статус отражает реальное понимание, а не количество отмеченных карточек.</p></header><div className="filters" aria-label="Фильтры маршрута">{filters.map(item => <button key={item.value} className={filter === item.value ? 'active' : ''} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="roadmap">{shown.map(({ stage, items }) => { const completed = stage.topicIds.filter(id => (state.progress[id]?.status ?? 0) === 3).length; return <section className="stage" key={stage.id}><div className="stage-index"><span>{stage.number}</span><small>МЕСЯЦ {stage.month}</small></div><div className="stage-body"><p className="eyebrow">ЭТАП {stage.number}</p><h2>{stage.title}</h2><p>{stage.description}</p><ProgressBar value={completed / stage.topicIds.length * 100} detail={`${completed} / ${stage.topicIds.length} освоено`} /><div className="topic-list">{items.map(topic => { const item = state.progress[topic.id]; const status = item?.status ?? 0; return <button className={`topic-row s${status}`} onClick={() => onTopic(topic.id)} key={topic.id}><span className="topic-code">{topic.id.toUpperCase()}</span><span>{topic.title}<small>{topic.description}</small></span><span className="confidence" title="Confidence">C{item?.confidence ?? 0}</span><i>{['—','ТЕОРИЯ','ПРАКТИКА','ОБЪЯСНЮ'][status]}</i></button>; })}</div><div className="checkpoint"><b>CHECKPOINT</b><ul>{stage.checkpoint.map(item => <li key={item}>{item}</li>)}</ul><div>{(['Нет', 'Частично', 'Да'] as const).map((label, index) => <button key={label} className={state.checkpoints[stage.id] === index ? 'active' : ''} onClick={() => onCheckpoint(stage.id, index as 0|1|2)}>{label}</button>)}</div></div></div></section>; })}</div>{shown.length === 0 && <div className="empty">По этому фильтру пока нет тем. Попробуй снять ограничение.</div>}</div>;
}
