import { useState } from 'react';
import { stages, topics } from '../data/curriculum';
import type { DailyLog, UserState } from '../types';
import { dateKey } from '../utils/date';
const quick = [15,30,45,60,90,120];
export function TodayPage({ state, onSave }: { state: UserState; onSave: (log: DailyLog) => void }) {
  const existing = state.dailyLogs.find(log => log.date === dateKey()); const [selected, setSelected] = useState<string[]>(existing?.topicIds ?? []); const [minutes, setMinutes] = useState(existing?.minutes ?? 30); const [custom, setCustom] = useState(''); const [learned, setLearned] = useState(existing?.learned ?? ''); const [practiced, setPracticed] = useState(existing?.practiced ?? ''); const [explanation, setExplanation] = useState(existing?.explanation ?? ''); const [unclear, setUnclear] = useState(existing?.unclear ?? ''); const [usefulness, setUsefulness] = useState(existing?.usefulness ?? 3); const [saved, setSaved] = useState(false);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); const submit = (event: React.FormEvent) => { event.preventDefault(); onSave({ id: existing?.id ?? crypto.randomUUID(), date: dateKey(), topicIds: selected, minutes: custom ? Number(custom) || minutes : minutes, learned, practiced, explanation, unclear, usefulness, createdAt: existing?.createdAt ?? new Date().toISOString() }); setSaved(true); };
  return <div className="page today"><header className="page-heading"><p className="eyebrow">ЖУРНАЛ ДНЯ // {dateKey()}</p><h1>Сегодня</h1><p>Запиши факт работы — коротко, без лишней отчётности. После сохранения день появится в календаре.</p></header><form className="journal" onSubmit={submit}><fieldset><legend>Что изучал сегодня?</legend><div className="topic-picker">{stages.map(stage => <div key={stage.id}><b>ЭТАП {stage.number} // {stage.title}</b>{stage.topicIds.map(id => <label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={() => toggle(id)} />{topics.find(topic => topic.id === id)?.title}</label>)}</div>)}</div></fieldset><fieldset><legend>Сколько времени?</legend><div className="quick-time">{quick.map(value => <button type="button" key={value} className={minutes === value && !custom ? 'active' : ''} onClick={() => {setMinutes(value); setCustom('');}}>{value < 60 ? `${value} минут` : `${value / 60} ч`}</button>)}<label>Другое <input type="number" min="1" value={custom} onChange={event => setCustom(event.target.value)} aria-label="Другое количество минут" /> мин</label></div></fieldset><label>Что нового узнал?<textarea required value={learned} onChange={event => setLearned(event.target.value)} placeholder="Коротко зафиксируй главный вывод." /></label><label>Что сделал руками?<textarea value={practiced} onChange={event => setPracticed(event.target.value)} placeholder="Лаборатория, команда, код, разбор HTTP-запроса, исправление уязвимости…" /></label><label>Объяснение своими словами<textarea value={explanation} onChange={event => setExplanation(event.target.value)} placeholder="Как бы ты объяснил главное человеку без технического опыта?" /></label><label>Что осталось непонятно?<textarea value={unclear} onChange={event => setUnclear(event.target.value)} placeholder="Это станет хорошей отправной точкой для следующей сессии." /></label><fieldset><legend>Насколько полезной была сегодняшняя сессия?</legend><div className="rating">{[1,2,3,4,5].map(value => <button type="button" key={value} className={usefulness === value ? 'active' : ''} onClick={() => setUsefulness(value)}>{value}</button>)}</div></fieldset><button className="primary" type="submit">СОХРАНИТЬ ЗАПИСЬ</button>{saved && <span className="saved">ЗАПИСЬ СОХРАНЕНА // СОХРАНЕНО ЛОКАЛЬНО</span>}</form></div>;
}
