import { useState } from 'react';
import { resources, stages } from '../data/curriculum';
import type { KnowledgeStatus, RoadmapTopic, TopicProgress } from '../types';

const names = ['Не начинал', 'Изучаю', 'Практиковал', 'Могу объяснить'];
export function TopicPanel({ topic, progress, onClose, onSave }: { topic: RoadmapTopic; progress?: TopicProgress; onClose: () => void; onSave: (patch: Partial<TopicProgress>) => void }) {
  const [notes, setNotes] = useState(progress?.notes ?? ''); const [explanation, setExplanation] = useState(progress?.explanation ?? ''); const [confidence, setConfidence] = useState(progress?.confidence ?? 0); const related = resources.filter(resource => resource.relatedTopicIds.includes(topic.id)); const stage = stages.find(item => item.id === topic.stageId);
  const save = () => { onSave({ notes, explanation, confidence }); onClose(); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="topic-panel" role="dialog" aria-modal="true" aria-labelledby="topic-title" onMouseDown={event => event.stopPropagation()}><button className="close" onClick={onClose} aria-label="Закрыть">×</button><p className="eyebrow">ЭТАП {stage?.number} // {stage?.title}</p><h2 id="topic-title">{topic.title}</h2><p className="lead">{topic.description}</p><div className="split-note"><b>Зачем AppSec-инженеру</b><p>{topic.why}</p>{topic.prerequisites?.length ? <><b>Предварительные знания</b><p>{topic.prerequisites.join(', ')}</p></> : null}</div><section><h3>Подтемы курса</h3><ol className="subtopic-list">{topic.subtopics.map(subtopic => <li key={subtopic.id}><b>{subtopic.title}</b><span>{subtopic.description}</span></li>)}</ol></section><fieldset><legend>Статус знания</legend><div className="status-options">{names.map((name, index) => <button key={name} className={(progress?.status ?? 0) === index ? `status s${index} selected` : `status s${index}`} onClick={() => onSave({ status: index as KnowledgeStatus })}>{index}. {name}</button>)}</div></fieldset><label>Уверенность <output>{confidence}/5</output><input type="range" min="0" max="5" value={confidence} onChange={event => setConfidence(Number(event.target.value))} /></label><label>Личные заметки<textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Наблюдения, команды, ссылки, выводы…" /></label><label>Объясни своими словами<textarea value={explanation} onChange={event => setExplanation(event.target.value)} placeholder="Представь, что объясняешь тему человеку, который вообще не занимается безопасностью." /></label>{topic.practice?.length ? <section><h3>Практика</h3><ul>{topic.practice.map(item => <li key={item}>{item}</li>)}</ul></section> : null}<section><h3>Самопроверка</h3><ul>{topic.questions?.map(question => <li key={question}>{question}</li>)}</ul></section><section><h3>Материалы</h3>{related.length ? related.map(resource => <a className="resource-link" key={resource.id} href={resource.url} target="_blank" rel="noreferrer"><span>{resource.type} · {resource.language}</span>{resource.title} ↗</a>) : <p className="muted">Связанные материалы появятся в библиотеке по мере расширения программы.</p>}</section><button className="primary" onClick={save}>СОХРАНИТЬ ЗАПИСИ</button></section></div>;
}
